# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photosequence_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Photosequence_gen(object):
    def setupUi(self, Photosequence_gen):
        Photosequence_gen.setObjectName("Photosequence_gen")
        Photosequence_gen.resize(582, 456)
        self.gridLayout_2 = QtWidgets.QGridLayout(Photosequence_gen)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_6 = QtWidgets.QToolButton(Photosequence_gen)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 4, 2, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(Photosequence_gen)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Photosequence_gen)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(Photosequence_gen)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Photosequence_gen)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(Photosequence_gen)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Photosequence_gen)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(Photosequence_gen)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Photosequence_gen)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(Photosequence_gen)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Photosequence_gen)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Photosequence_gen)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(Photosequence_gen)
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 0, 2, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(Photosequence_gen)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(Photosequence_gen)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rb_classic = QtWidgets.QRadioButton(Photosequence_gen)
        self.rb_classic.setChecked(True)
        self.rb_classic.setObjectName("rb_classic")
        self.buttonGroup = QtWidgets.QButtonGroup(Photosequence_gen)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rb_classic)
        self.horizontalLayout_5.addWidget(self.rb_classic)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rb_micmac = QtWidgets.QRadioButton(Photosequence_gen)
        self.rb_micmac.setEnabled(False)
        self.rb_micmac.setChecked(False)
        self.rb_micmac.setObjectName("rb_micmac")
        self.buttonGroup.addButton(self.rb_micmac)
        self.horizontalLayout_7.addWidget(self.rb_micmac)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Photosequence_gen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Photosequence_gen)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_epsg = QtWidgets.QLineEdit(Photosequence_gen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_epsg.sizePolicy().hasHeightForWidth())
        self.le_epsg.setSizePolicy(sizePolicy)
        self.le_epsg.setObjectName("le_epsg")
        self.horizontalLayout.addWidget(self.le_epsg)
        self.buttonBox = QtWidgets.QDialogButtonBox(Photosequence_gen)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)

        self.retranslateUi(Photosequence_gen)
        self.buttonBox.accepted.connect(Photosequence_gen.accept)
        self.buttonBox.rejected.connect(Photosequence_gen.reject)
        QtCore.QMetaObject.connectSlotsByName(Photosequence_gen)

    def retranslateUi(self, Photosequence_gen):
        _translate = QtCore.QCoreApplication.translate
        Photosequence_gen.setWindowTitle(_translate("Photosequence_gen", "Dialog"))
        self.toolButton_6.setToolTip(_translate("Photosequence_gen", "trajectoire ponctuelle au format gpkg"))
        self.toolButton_6.setText(_translate("Photosequence_gen", "..."))
        self.toolButton_2.setToolTip(_translate("Photosequence_gen", "Mise en place absolue de caméra au format xml MicMac"))
        self.toolButton_2.setText(_translate("Photosequence_gen", "..."))
        self.label_7.setText(_translate("Photosequence_gen", "Trajectoire (couche de points GPKG)"))
        self.label_2.setText(_translate("Photosequence_gen", "Fichier de calibration de caméra"))
        self.label_6.setText(_translate("Photosequence_gen", "Dossier contenant les images"))
        self.toolButton_3.setToolTip(_translate("Photosequence_gen", "Fichier de l\'orientation de l\'image au format xml MicMac"))
        self.toolButton_3.setText(_translate("Photosequence_gen", "..."))
        self.label_3.setText(_translate("Photosequence_gen", "Fichier de l\'orientation de l\'image"))
        self.toolButton_7.setToolTip(_translate("Photosequence_gen", "Mise en place absolue de caméra au format xml MicMac"))
        self.toolButton_7.setText(_translate("Photosequence_gen", "..."))
        self.toolButton_5.setToolTip(_translate("Photosequence_gen", "Image pour laquelle on souhaite avoir une photoséquence, au format PNG"))
        self.toolButton_5.setText(_translate("Photosequence_gen", "..."))
        self.label_8.setText(_translate("Photosequence_gen", "Repertoire de sortie"))
        self.rb_classic.setText(_translate("Photosequence_gen", "Calcul avec un algorithme classique"))
        self.rb_micmac.setText(_translate("Photosequence_gen", "Calcul avec MicMac"))
        self.textBrowser.setHtml(_translate("Photosequence_gen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "hr { height: 1px; border-width: 0; }\n"
        "li.unchecked::marker { content: \"\\2610\"; }\n"
        "li.checked::marker { content: \"\\2612\"; }\n"
        "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\n"
        "<span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">\n"
        "Ce plugin permet d'automatiser la génération de photo-séquences. Pour ce faire, vous devez fournir plusieurs sources de données :<br />\n"
        "<ul>\n"
        "<li>Le répertoire de sortie, où la photo-séquence sera stockée.</li>\n"
        "<li>Un fichier XML contenant la calibration de la caméra ainsi que son orientation.</li>\n"
        "<li>Le dossier contenant toutes les images et les masques MicMac associés.</li>\n"
        "<li>Le fichier GPKG de la trajectoire de l'aéronef.</li>\n"
        "<li>Enfin, le code EPSG du chantier MicMac.</li>\n"
        "</ul>\n"
        "Assurez-vous que toutes les informations nécessaires soient correctement renseignées.\n"
        "</span></p></body></html>"))
        self.label.setText(_translate("Photosequence_gen", "Code EPSG du chantier MicMac"))
        self.le_epsg.setPlaceholderText(_translate("Photosequence_gen", "2154, 3857, ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Photosequence_gen = QtWidgets.QDialog()
    ui = Ui_Photosequence_gen()
    ui.setupUi(Photosequence_gen)
    Photosequence_gen.show()
    sys.exit(app.exec_())
