# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhotosequenceGen
                                 A QGIS plugin
 Ce plugin permet de générer une photoséquence
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-10
        copyright            : (C) 2024 by Jules Rosier / BEA
        email                : jules.rosier@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PhotosequenceGen class from file PhotosequenceGen.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .photosequence_gen import PhotosequenceGen
    return PhotosequenceGen(iface)
