# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photosequence_gen_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Photosequence_gen(object):
    def setupUi(self, Photosequence_gen):
        Photosequence_gen.setObjectName("Photosequence_gen")
        Photosequence_gen.resize(507, 432)
        self.gridLayoutWidget = QtWidgets.QWidget(Photosequence_gen)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(29, 119, 461, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 2, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 2, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 2, 2, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 3, 2, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 4, 2, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Photosequence_gen)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 360, 461, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.horizontalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.textBrowser = QtWidgets.QTextBrowser(Photosequence_gen)
        self.textBrowser.setGeometry(QtCore.QRect(30, 20, 461, 91))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Photosequence_gen)
        self.buttonBox.accepted.connect(Photosequence_gen.accept)
        self.buttonBox.rejected.connect(Photosequence_gen.reject)
        QtCore.QMetaObject.connectSlotsByName(Photosequence_gen)

    def retranslateUi(self, Photosequence_gen):
        _translate = QtCore.QCoreApplication.translate
        Photosequence_gen.setWindowTitle(_translate("Photosequence_gen", "Dialog"))
        self.label_3.setText(_translate("Photosequence_gen", "Fichier de l\'orientation de l\'image"))
        self.label.setText(_translate("Photosequence_gen", "Fichier de mise en place absolue de caméra"))
        self.label_5.setText(_translate("Photosequence_gen", "Trajectoire en ligne"))
        self.toolButton.setToolTip(_translate("Photosequence_gen", "Mise en place absolue de caméra au format xml MicMac"))
        self.toolButton.setText(_translate("Photosequence_gen", "..."))
        self.toolButton_2.setToolTip(_translate("Photosequence_gen", "Mise en place absolue de caméra au format xml MicMac"))
        self.toolButton_2.setText(_translate("Photosequence_gen", "..."))
        self.toolButton_3.setToolTip(_translate("Photosequence_gen", "Fichier de l\'orientation de l\'image au format xml MicMac"))
        self.toolButton_3.setText(_translate("Photosequence_gen", "..."))
        self.toolButton_5.setToolTip(_translate("Photosequence_gen", "Image pour laquelle on souhaite avoir une photoséquence, au format PNG"))
        self.toolButton_5.setText(_translate("Photosequence_gen", "..."))
        self.toolButton_4.setToolTip(_translate("Photosequence_gen", "Trajectoire linéaire au format gpkg"))
        self.toolButton_4.setText(_translate("Photosequence_gen", "..."))
        self.toolButton_6.setToolTip(_translate("Photosequence_gen", "trajectoire ponctuelle au format gpkg"))
        self.toolButton_6.setText(_translate("Photosequence_gen", "..."))
        self.label_6.setText(_translate("Photosequence_gen", "Image pour la photoséquence"))
        self.label_2.setText(_translate("Photosequence_gen", "Fichier de calibration de caméra"))
        self.label_7.setText(_translate("Photosequence_gen", "Trajectoire ponctuelle"))
        self.label_4.setText(_translate("Photosequence_gen", "Lancement du traitement"))
        self.textBrowser.setHtml(_translate("Photosequence_gen", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ce plugin permet d\'automatiser la génération de photoséquences. Pour cela vous devez renseigner plusieurs sources de données.<br />La mise en place absolue et la calibration de caméra, ainsi que l\'orientation de l\'image au format XML MicMac.<br />L\'image au format PNG dont vous souhaitez avoir la photoséquences.<br />Les trajectoires linéaire et ponctuelle de l\'aéronef étudiée (coordonée en XXXX)</p></body></html>"))

