# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhotosequenceGenDialog
                                 A QGIS plugin
 Ce plugin permet de générer une photoséquence
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-10
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Jules Rosier / BEA
        email                : jules.rosier@ensg.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from .photosequence_gen_dialog_UI import Ui_Photosequence_gen
 


class PhotosequenceGenDialog(QtWidgets.QDialog, Ui_Photosequence_gen):
    def __init__(self, parent=None):
        """Constructor."""
        super(PhotosequenceGenDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
